title: The Shelby GT350 Lemonted Edition
description: Exclusive information about the world's most famous Shelby GT350 lemonted edition.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate